-- INSERT INTO pneus (brand, model) VALUES ('Michelin', 'Pilot Sport 4S');
-- INSERT INTO pneus (brand, model) VALUES ('Michelin', 'Pilot Sport 4');
-- INSERT INTO pneus (brand, model) VALUES ('Michelin', 'Pilot Sport 3');
-- INSERT INTO pneus (brand, model) VALUES ('Michelin', 'Pilot Sport 2');
--
--
-- INSERT INTO motor(cilindrada, model, potencia) VALUES (2000, '1.6 16V', 120);
-- INSERT INTO motor(cilindrada, model, potencia) VALUES (2000, '1.6 16V', 150);
-- INSERT INTO motor(cilindrada, model, potencia) VALUES (2000, '1.6 16V', 180);
-- INSERT INTO motor(cilindrada, model, potencia) VALUES (2000, '1.6 16V', 200);
--
--

